# 应用服务 WEB 访问端口
server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kob?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Yungam123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379




